# Generated by Django 3.1.3 on 2020-11-21 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application1', '0002_auto_20201120_1409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produit',
            name='image',
            field=models.FileField(upload_to='img'),
        ),
    ]
