# Generated by Django 3.1.3 on 2020-11-22 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application1', '0003_auto_20201121_1239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorie',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='categorie',
            name='nom_categorie',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='produit',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='img'),
        ),
        migrations.AlterField(
            model_name='produit',
            name='prix',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='produit',
            name='quantite',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
