# Generated by Django 3.1.3 on 2020-11-24 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application1', '0007_auto_20201123_1925'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produit',
            old_name='image',
            new_name='photo',
        ),
    ]
