# Generated by Django 3.1.3 on 2020-11-27 10:30

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('application1', '0010_auto_20201124_1156'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='date_creation',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 11, 27, 10, 30, 37, 935179, tzinfo=utc), verbose_name='Date création'),
        ),
    ]
