# Generated by Django 3.1.3 on 2020-11-27 16:23

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('application1', '0013_auto_20201127_1318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produit',
            name='date_creation',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 11, 27, 16, 23, 3, 994041, tzinfo=utc), verbose_name='Date création'),
        ),
    ]
